---
- name: "Install /tmp/grafana_8.4.3_amd64.deb"
  get_url:
    url: https://pkgs.frameworkhosting.com/grafana_8.4.3_amd64.deb
    dest: "/tmp/grafana_8.4.3_amd64.deb"
    checksum: sha256:a370f4b1075da644fd9be7d5a683ca070a1442b0a502e36c6ec7d8fff60061c2

- name: "Install Grafana Package"
  apt:
    deb: '/tmp/grafana_8.4.3_amd64.deb'
    state: present

- name: "Install /etc/nginx/sites-available/{{ config.grafana.domain }}.conf"
  copy:
    dest: "/etc/nginx/sites-available/{{ config.grafana.domain }}.conf"
    src: "{{ role_path }}/files/nginx/grafana.conf"
    owner: root
    group: root
    mode: 0644

- name: "Install /etc/grafana/grafana.ini"
  template:
    src: "{{ role_path }}/templates/grafana.ini.j2"
    dest: /etc/grafana/grafana.ini
    owner: root
    group: root
    mode: 0644

- name: "Create symlink for nginx domain: {{ config.grafana.domain }}"
  file:
    state: link
    path: "/etc/nginx/sites-enabled/{{ config.grafana.domain }}.conf"
    src: "/etc/nginx/sites-available/{{ config.grafana.domain }}.conf"

- name: Start & Enable grafana
  service:
    name: grafana-server
    enabled: true
    state: restarted
